# Generated by Django 5.2.4 on 2025-07-13 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_exchangeproposal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangeproposal',
            name='ad_reciever',
        ),
        migrations.AddField(
            model_name='exchangeproposal',
            name='ad_receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recieved_proposals', to='ads.ad'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exchangeproposal',
            name='ad_sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_proposals', to='ads.ad'),
        ),
    ]
